User-Management-System/ITP---2019-master/Inventory_management/Models/salary.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory_management.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class salary
    {





        [Required(ErrorMessage = "Employee ID has to be filled")]
        [Range(1, 10000)]
        public Nullable<int> empId { get; set; }


        [Required(ErrorMessage = "Basic Salary has to be filled")]
        [Range(1, 100000000)]
        public Nullable<double> basic { get; set; }

        [Required(ErrorMessage = "O/T hours has to be filled")]
        [Range(1, 30)]

        public Nullable<double> othours { get; set; }

        [Required(ErrorMessage = "O/T rate has to be filled")]
        [Range(1, 1000)]
        public Nullable<double> otrate { get; set; }

        [Required(ErrorMessage = "Bonus has to be filled")]
        [Range(1, 1000)]
        public Nullable<double> bonus { get; set; }
        public Nullable<double> otpay { get; set; }
        public Nullable<double> deduction { get; set; }
        public Nullable<double> netsal { get; set; }
    }
}

User-Management-System/ITP---2019-master/Inventory_management/Controllers/SalaryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Inventory_management.Models;

namespace Inventory_management.Controllers
{
    public class SalaryController : Controller
    {
        // GET: Salary
        public ActionResult Index()
        {
            salary sal = new salary();
            return View(sal);
        }

        [HttpPost]
        public ActionResult Index(salary s)
        {
            if (s.basic > 30000)
            {
                s.deduction = s.basic * (5.0 / 100);

            }
            else if (s.basic > 15000)
            {
                s.deduction = s.basic * (2.0 / 100);

            }
            else
            {
                s.deduction = 0;

            }
            s.otpay = s.othours * s.otrate;
            s.netsal = s.basic + s.bonus + s.otpay - s.deduction;
            //s.netsal = s.basic + s.bonus +( s.othours* s.otrate) - s.deduction;
            return View(s);
        }


        public ActionResult Details(int id)
        {
            using (inventorymgtEntities employeeModels = new inventorymgtEntities())
            {
                //return View(employeeModels.salaries.ToList());
                return View();
            }
        }

    }

}

User-Management-System/ITP---2019-master/Inventory_management/Views/Salary/Index.cshtml
@using Inventory_management.Models
@model Inventory_management.Models.salary

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/adminView/adminEmployee4.cshtml";
}




<html>
<head>

</head>
<body>
    <br />
    <h4><b>Salary Management</b></h4>
    <br />
    <div class="row">
        @using (Html.BeginForm("/Index", "Salary", FormMethod.Post))
        {

            <div class="form-group">
                <lable for="name"><b>EmpId</b></lable>
                <input type="text" class="form-control" id="empId" name="empId" value="@Model.empId" />
            </div>


            <div class="form-group">
                <lable for="name"><b>Basic Salary</b></lable>
                <input type="text" class="form-control" id="basic" name="basic" value="@Model.basic" />
            </div>
            <div class="form-group">
                <lable for="name"><b>O/T hours</b></lable>
                <input type="text" class="form-control" id="othours" name="othours" value="@Model.othours" />
            </div>


            <div class="form-group">
                <lable for="name"><b>O/T Rate</b></lable>
                <input type="text" class="form-control" id="otrate" name="otrate" value="@Model.otrate" />
            </div>

            <div class="form-group">
                <lable for="name"><b>Bonus</b></lable>
                <input type="text" class="form-control" id="bonus" name="bonus" value="@Model.bonus" />
            </div>
            <div class="form-group">
                <lable for="name"><b>O/T Pay</b></lable>
                <input type="text" class="form-control" id="otpay" name="otpay" value="@Model.otrate" disabled />
            </div>
            <div class="form-group">
                <lable for="name"><b>Deduction</b></lable>
                <input type="text" class="form-control" id="deduction" name="deduction" value="@Model.deduction" disabled />
            </div>

            <div class="form-group">
                <lable for="name"><b>NetSalary</b></lable>
                <input type="text" class="form-control" id="netsal" name="netsal" value="@Model.netsal" disabled />
            </div>



            <button type="submit" class="btn btn-info" id="add" value="add">Calculate</button>

        }



    </div>

</body>



</html>