User-Management-System/ITP---2019-master/Inventory_management/Controllers/FinanceController.cs
using Inventory_management.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Inventory_management.Controllers
{
    public class FinanceController : Controller
    {

        DBModel db = new DBModel();

        // GET: Finance
        [HttpGet]
        public ActionResult income()
        {
            return View(db.incomeData());
        }

        [HttpGet]
        public ActionResult daily()
        {
            return View(db.dailyData());
        }

       [HttpPost]
        public ActionResult InsertData(String date, String category, String cash, String pos, String amount)
        {

            if (date != "" && category != "" && cash != "" && pos != "" && amount != "")
            {
                income income = new income();

                income.date = date;
                income.category = category;
                income.cash = Double.Parse(cash);
                income.pos = Double.Parse(pos);
                income.total = Double.Parse(amount);

                db.incomeInsert(income);

                return Json("success", JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json("error", JsonRequestBehavior.AllowGet);
            }

        }

       [HttpPost]
        public ActionResult editIncome(String id,String date, String category, String cash, String pos, String amount)
        {

            if (id != "" && date != "" && category != "" && cash != "" && pos != "" && amount != "")
            {
                income income = new income();

                income.id = int.Parse(id);
                income.date = date;
                income.category = category;
                income.cash = Double.Parse(cash);
                income.pos = Double.Parse(pos);
                income.total = Double.Parse(amount);

                db.incomeEdit(income);

                return Json("success", JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json("error", JsonRequestBehavior.AllowGet);
            }

        }

        [HttpPost]
        public ActionResult incomeDelete(String id)
        {

            if (id != "")
            {
                income income = new income();

                income.id = int.Parse(id);

                db.deleteIncome(income);

                return Json("success", JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json("error", JsonRequestBehavior.AllowGet);
            }

        }

        [HttpPost]
        public ActionResult InsertDailyData(String date, String savings, String category, String amount)
        {

            if (date != "" && category != "" && savings != "" && amount != "")
            {
                daily daily = new daily();

                daily.date = date;
                daily.category = category;
                daily.savings = Double.Parse(savings);
                daily.amount = Double.Parse(amount);

                db.dailyInsert(daily);

                Session["success"] = 1;

                return Json("success", JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json("error", JsonRequestBehavior.AllowGet);
            }

        }

       [HttpPost]
        public ActionResult editDaily(String id, String date, String category, String savings, String amount)
        {

            if (id != "" && date != "" && category != "" && savings != "" && amount != "")
            {
                daily daily = new daily();

                daily.id = int.Parse(id);
                daily.date = date;
                daily.category = category;
                daily.savings = Double.Parse(savings);
                daily.amount = Double.Parse(amount);

                db.editDaily(daily);

                Session["success"] = 2;

                return Json("success", JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json("error", JsonRequestBehavior.AllowGet);
            }

        }

        [HttpPost]
        public ActionResult dailyDelete(String id)
        {

            if (id != "")
            {
                daily daily = new daily();

                daily.id = int.Parse(id);

                db.deleteDaily(daily);

                Session["success"] = 3;

                return Json("success", JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json("error", JsonRequestBehavior.AllowGet);
            }

        }

    }

}

User-Management-System/ITP---2019-master/Inventory_management/Controllers/InventoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Inventory_management.Models;
using System.Data.Entity;

namespace Inventory_management.Controllers
{
    public class InventoryController : Controller
    {
        // GET: InventoryC:\Users\Akaam Zain\Documents\SLIIT\ITP\Sky Gym\Inventory_management\Controllers\InventoryController.cs
        public ActionResult Index()
        {
            using (inventorymgtEntities invtModel = new inventorymgtEntities())
            {
                
                return View(invtModel.inventories.ToList());

            }

        }

        // GET: Inventory/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Inventory/Create
        public ActionResult Create()
        {

            return View();
        }


        // POST: Inventory/Create
        [HttpPost]
        public ActionResult Create(inventory invent)
        {
            try
            {
                using (inventorymgtEntities invtModel = new inventorymgtEntities())
                {
                   
                    invtModel.inventories.Add(invent);
                    invtModel.SaveChanges();
                }
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }


        public ActionResult Reorder()
        {

            using (inventorymgtEntities in1 = new inventorymgtEntities())
            {

                return View(in1.inventories.ToList().Where(x => x.quantity < 5 && x.catergory.Equals("Store")));

            }
        }


        public ActionResult ReorderDetails(int id)
        {
            using (inventorymgtEntities invtModel = new inventorymgtEntities())
            {
                return View(invtModel.inventories.Where(x => x.itemCode == id).FirstOrDefault());

            }
        }



        // GET: Inventory/Edit/5
        public ActionResult Edit(int id)
        {
            using (inventorymgtEntities invtModel = new inventorymgtEntities())
            {
                return View(invtModel.inventories.Where(x => x.itemCode == id).FirstOrDefault());

            }


        }

        // POST: Inventory/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, inventory invent)
        {
            try
            {
                using (inventorymgtEntities invtModel = new inventorymgtEntities())
                {
                    invtModel.Entry(invent).State = EntityState.Modified;
                    invtModel.SaveChanges();
                }

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Inventory/Delete/5
        public ActionResult Delete(int id)
        {
            using (inventorymgtEntities invtModel = new inventorymgtEntities())
            {
                return View(invtModel.inventories.Where(x => x.itemCode == id ).FirstOrDefault());

            }


        }





        // POST: Inventory/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                using (inventorymgtEntities invtModel = new inventorymgtEntities())
                {

                    inventory invent = invtModel.inventories.Where(x => x.itemCode == id).FirstOrDefault();
                    invtModel.inventories.Remove(invent);
                    invtModel.SaveChanges();

                }
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

User-Management-System/ITP---2019-master/Inventory_management/Controllers/OrderController.cs
using CrystalDecisions.CrystalReports.Engine;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Inventory_management.Models;
using System.IO;

namespace Inventory_management.Controllers
{
    public class OrderController : Controller
    {
        inventorymgtEntities db = new inventorymgtEntities();
        // GET: Order
        public ActionResult Index()
        {
            return View(db.orders.ToList());
        }

        // GET: Order/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.BadRequest);
            }
            var order1 = db.orders.Find(id);
            if(order1 == null)
            {
                return HttpNotFound();
            }
            return View(order1);
        }

        public ActionResult ExportOrderListing()
        {
            ReportDocument rd = new ReportDocument();
            rd.Load(Path.Combine(Server.MapPath("~/Report/Order/OrderReport.rpt")));
            rd.SetDataSource(db.orders.ToList());          

            Response.Buffer = false;
            Response.ClearContent();
            Response.ClearHeaders();

            Stream str = rd.ExportToStream(CrystalDecisions.Shared.ExportFormatType.PortableDocFormat);
            str.Seek(0, SeekOrigin.Begin);

            string savedFileName = string.Format("OrderReport_{0}", DateTime.Now);
            return File(str,"application/pdf", savedFileName);
        }
    }
}

User-Management-System/ITP---2019-master/Inventory_management/Controllers/ScheduleController.cs
using Inventory_management.Models;
using Inventory_management.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Runtime.Remoting.Contexts;
using System.Web;
using System.Web.Mvc;



namespace Inventory_management.Controllers
{
    public class ScheduleController : Controller
    {

        //DBMod dbs = new DBMod();
        //public ActionResult New()
        //{
            
        //        var employeelist = dbs.employees.ToList();

            
            
        //        var viewModel = new NewScheduleViewModel
        //        {
        //            employeeType = employeelist
        //        };

        //    return View(viewModel);
            

            
            
        //}

        



        //private static List<SelectListItem> Getemployee()
        //{


        //    DBMod db = new DBMod();
        //    List<SelectListItem> employeelist = (from e in db.employees.AsEnumerable()
        //                                         where e.Shift == "Morning"
        //                                         select new SelectListItem
        //                                         {
        //                                             Text = e.Name,
        //                                             Value = e.EmpID.ToString()
        //                                         }).ToList();

        //    employeelist.Insert(0, new SelectListItem { Text = "Select Trainer", Value = "" });
        //    return employeelist;
        //}


        // GET: Schedule
        public ActionResult Index()
        {
            using (inventorymgtEntities mv = new inventorymgtEntities())
            {
                return View(mv.schedules.ToList());
            }
        }

        // GET: Schedule/Details/5
        public ActionResult Details(int id)
        {
            schedule sc = new schedule();
            using (inventorymgtEntities db = new inventorymgtEntities())
            {
                sc = db.schedules.Where(m => m.ID == id).FirstOrDefault();
            }
            return View(sc);
        }

        // GET: Schedule/Create
        public ActionResult Create()
        {
            //List<SelectListItem> employeeList = Getemployee();
            return View();
        }

        // POST: Schedule/Create
        [HttpPost]
        public ActionResult Create(schedule sc)
        {
            try
            {
                string fileName = Path.GetFileNameWithoutExtension(sc.ImageFile.FileName);
                string extension = Path.GetExtension(sc.ImageFile.FileName);
                string imageName = fileName + DateTime.Now.ToString("yymmssfff")+extension;
                sc.Image = "~/Content/Images/" + imageName;
                imageName = Path.Combine(Server.MapPath("~/Content/Images/"), imageName);
                sc.ImageFile.SaveAs(imageName);
                using (inventorymgtEntities mv = new inventorymgtEntities())
                {

                    mv.schedules.Add(sc);
                    mv.SaveChanges();

                }
                
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    

        // GET: Schedule/Edit/5
        public ActionResult Edit(int id)
        {
            using (inventorymgtEntities db = new inventorymgtEntities())
            {
                return View(db.schedules.Where(x=>x.ID==id).FirstOrDefault());
            }
                
        }

        // POST: Schedule/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, schedule sc)
        { 
            try
            {
                using (inventorymgtEntities db = new inventorymgtEntities())
                {
                    
                   db.Entry(sc).State = EntityState.Modified;
                    if (sc.Image == null)
                    {
                        var scheduleContext = db.Entry(sc);
                        scheduleContext.State = EntityState.Modified;

                        var clientValues = scheduleContext.CurrentValues.Clone().ToObject();
                        scheduleContext.Reload();
                        scheduleContext.CurrentValues.SetValues(clientValues);

                        var currentValues = scheduleContext.Entity;
                        var databaseValues = (schedule)scheduleContext.OriginalValues.ToObject();

                        scheduleContext.Entity.Image = databaseValues.Image;
                    }
                   db.SaveChanges();
                }
                    // TODO: Add update logic here

                    return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Schedule/Delete/5
        public ActionResult Delete(int id = 0)
        {

            using (inventorymgtEntities mv = new inventorymgtEntities())
            {
                return View(mv.schedules.Where(x => x.ID == id).FirstOrDefault());

            }

        }

        // POST: Schedule/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here
                using (inventorymgtEntities mv = new inventorymgtEntities())
                {
                    schedule sc = mv.schedules.Where(x => x.ID == id).FirstOrDefault();
                    mv.schedules.Remove(sc);
                    mv.SaveChanges();


                }
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }



    }
}

User-Management-System/ITP---2019-master/Inventory_management/Views/Shared/adminView/admin.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="../../../Content/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="../../../Content/bootstrap-grid.min.css">

</head>
<body>
    

        <header>

            <div class="col-sm-12 ">

                <nav class="navbar navbar-expand-lg py-2 " id="mainNav">
                    <div class="container">
                        <a class="navbar-brand js-scroll-trigger lead font-weight-bold text-danger" href="#page-top ">
                            <img src="LOGO.jpg" alt="SKY GYM" class="img-thumbnail" style="width:100px">
                        </a>

                        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse"
                                data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false"
                                aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon"></span>
                        </button>
                        <div class="collapse navbar-collapse" id="navbarResponsive">
                            <ul class="navbar-nav ml-auto my-2 my-lg-0"></ul>

                            <button type="button" class="btn btn-md btn-outline-danger">LOGOUT</button>
                        </div>
                    </div>
                </nav>
            </div>

        </header>
   

    <div class="row">
        <div class="col-sm-2 bg-dark">    </div>

        <div class="col-sm-10 bg-dark text-white">
            <a href="#" class=" col-sm-3 list-group-item bg-secondary list-group-item-action text-white text-center float-left">Inventory</a>
            <a href="@Url.Action("Index", "Supplier")" class=" col-sm-3 list-group-item  bg-dark list-group-item-action text-white text-center float-left">Supplier</a>

        </div>
    </div>
    <div class="container-fluid">
        <div class="row " style="height: 680px;">
            <div class="col-sm-2 bg-dark">
                <a href="@Url.Action("Index_Copy","Search")" class="list-group-item  bg-dark list-group-item-action text-white text-center">User Profile</a> <br>

                <a href="@Url.Action("Index","Employee")" class=" list-group-item bg-dark list-group-item-action text-white text-center">Employee Management</a> <br>

                <a href="@Url.Action("Index","Schedule")" class=" list-group-item  bg-dark  list-group-item-action text-white text-center">Schedule Management</a> <br>

                <a href="@Url.Action("Index","Deit")" class="list-group-item bg-dark list-group-item-action text-white text-center">Diet Plan Management </a> <br>

                <a href="@Url.Action("Index","Store")" class="list-group-item bg-dark list-group-item-action text-white text-center">Store Management</a> <br>

                <a href="@Url.Action("Index","Bill")" class="list-group-item bg-dark list-group-item-action text-white text-center">Payment Management</a> <br>

                <a href="@Url.Action("income","Finance")" class="list-group-item bg-dark list-group-item-action text-white text-center">Finance Management</a> <br>

                <a href="@Url.Action("Index","Inventory")" class="list-group-item bg-secondary list-group-item-action text-white text-center">Inventory Management</a> <br>

            </div>

            <div class="container body-content">
                @RenderBody()
                <hr />
                <footer>
                    <p>&copy; @DateTime.Now.Year - Sky Gym</p>
                </footer>
            </div>
        </div>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

User-Management-System/ITP---2019-master/Inventory_management/Views/Shared/adminView/adminEmployee.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="css/bootstrap.min.css">

    <link rel="stylesheet" type="text/css" href="css/bootstrap-grid.min.css">

</head>
<body>
    <header>

        <div class="col-sm-12 ">

            <nav class="navbar navbar-expand-lg py-2 " id="mainNav">
                <div class="container">
                    <a class="navbar-brand js-scroll-trigger lead font-weight-bold text-danger" href="#page-top ">
                        <img src="LOGO.jpg" alt="SKY GYM" class="img-thumbnail" style="width:100px">
                    </a>

                    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse"
                            data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false"
                            aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarResponsive">
                        <ul class="navbar-nav ml-auto my-2 my-lg-0"></ul>
                        <button type="button" class="btn btn-md btn-outline-danger">LOGOUT</button>
                    </div>
                </div>
            </nav>
        </div>

    </header>


    <div class="row">
        <div class="col-sm-2 bg-dark">    </div>

        <div class="col-sm-10 bg-dark text-white">
            <a href="@Url.Action("Index", "Employee")" class=" col-sm-3 list-group-item bg-secondary list-group-item-action text-white text-center float-left">Employee</a>
            <a href="@Url.Action("Index", "Attendance")" class=" col-sm-3 list-group-item  bg-dark list-group-item-action text-white text-center float-left">Attendance</a>
            <a href="@Url.Action("Index", "Leave")" class=" col-sm-3 list-group-item bg-dark list-group-item-action text-white text-center float-left">Leave</a>
            <a href="@Url.Action("Index", "Salary")" class=" col-sm-3 list-group-item  bg-dark list-group-item-action text-white text-center float-left">Salary</a>

        </div>
    </div>
    <div class="container-fluid">
        <div class="row " style="height: 680px;">
            <div class="col-sm-2 bg-dark">
                <a href="@Url.Action("Index","User")" class="list-group-item  bg-dark list-group-item-action text-white text-center">User Profile</a> <br>

                <a href="@Url.Action("Index","Employee")" class=" list-group-item bg-secondary list-group-item-action text-white text-center">Employee Management</a> <br>

                <a href="@Url.Action("Index","Schedule")" class=" list-group-item  bg-dark  list-group-item-action text-white text-center">Schedule Management</a> <br>

                <a href="@Url.Action("Index","Deit")" class="list-group-item bg-dark list-group-item-action text-white text-center">Diet Plan Management </a> <br>

                <a href="@Url.Action("Index","Store")" class="list-group-item bg-dark list-group-item-action text-white text-center">Store Management</a> <br>

                <a href="@Url.Action("Index","Bill")" class="list-group-item bg-dark list-group-item-action text-white text-center">Payment Management</a> <br>

                <a href="@Url.Action("income","Finance")" class="list-group-item bg-dark list-group-item-action text-white text-center">Finance Management</a> <br>

                <a href="@Url.Action("Index","Inventory")" class="list-group-item bg-dark list-group-item-action text-white text-center">Inventory Management</a> <br>

            </div>

            <div class="container body-content">
                @RenderBody()
                <hr />
                <footer>
                    <p>&copy; @DateTime.Now.Year - Sky Gym</p>
                </footer>
            </div>

            @Scripts.Render("~/bundles/jquery")
            @Scripts.Render("~/bundles/bootstrap")
            @RenderSection("scripts", required: false)
</body>
</html>

User-Management-System/ITP---2019-master/Inventory_management/Views/Shared/adminView/order.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="css/bootstrap.min.css">

    <link rel="stylesheet" type="text/css" href="css/bootstrap-grid.min.css">

</head>
<body>
    <header>

        <div class="col-sm-12 ">

            <nav class="navbar navbar-expand-lg py-2 " id="mainNav">
                <div class="container">
                    <a class="navbar-brand js-scroll-trigger lead font-weight-bold text-danger" href="#page-top ">
                        <img src="LOGO.jpg" alt="SKY GYM" class="img-thumbnail" style="width:100px">
                    </a>

                    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse"
                            data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false"
                            aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarResponsive">
                        <ul class="navbar-nav ml-auto my-2 my-lg-0"></ul>
                        <button type="button" class="btn btn-md btn-outline-danger">LOGOUT</button>
                    </div>
                </div>
            </nav>
        </div>

    </header>


    <div class="row">
        <div class="col-sm-2 bg-dark">    </div>

        <div class="col-sm-10 bg-dark text-white">
            <a href="@Url.Action("Index", "Store")" class=" col-sm-3 list-group-item bg-dark list-group-item-action text-white text-center float-left">Store</a>
            <a href="@Url.Action("Index", "Order")" class=" col-sm-3 list-group-item  bg-secondary list-group-item-action text-white text-center float-left">Order</a>

        </div>
    </div>
    <div class="container-fluid">
        <div class="row " style="height: 680px;">
            <div class="col-sm-2 bg-dark">

                <a href="@Url.Action("Index","User")" class="list-group-item  bg-dark list-group-item-action text-white text-center">User Profile</a> <br>

                <a href="@Url.Action("Index","Employee")" class=" list-group-item bg-dark list-group-item-action text-white text-center">Employee Management</a> <br>

                <a href="@Url.Action("Index","Schedule")" class=" list-group-item  bg-dark  list-group-item-action text-white text-center">Schedule Management</a> <br>

                <a href="@Url.Action("Index","Deit")" class="list-group-item bg-dark list-group-item-action text-white text-center">Diet Plan Management </a> <br>

                <a href="@Url.Action("Index","Store")" class="list-group-item bg-secondary list-group-item-action text-white text-center">Store Management</a> <br>

                <a href="@Url.Action("Index","Bill")" class="list-group-item bg-dark list-group-item-action text-white text-center">Payment Management</a> <br>

                <a href="@Url.Action("income","Finance")" class="list-group-item bg-dark list-group-item-action text-white text-center">Finance Management</a> <br>

                <a href="@Url.Action("Index","Inventory")" class="list-group-item bg-dark list-group-item-action text-white text-center">Inventory Management</a> <br>

            </div>

            <div class="container body-content">
                @RenderBody()
                <hr />
                <footer>
                    <p>&copy; @DateTime.Now.Year - Sky Gym</p>
                </footer>
            </div>

            @Scripts.Render("~/bundles/jquery")
            @Scripts.Render("~/bundles/bootstrap")
            @RenderSection("scripts", required: false)
</body>
</html>